# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d3024087054ecda4271273b1b6f4f0338c4ea05e891cc8b71f4da0a68c014d8e30e8eb15bbd2af121e48921f10ade62552c3477656c2cf4567f9939834e81db

test:
  secret_key_base: 06d3db0d12da6bd82f4f01b6ff30c9b2160e7e9779a9b6207786b85efb0f617eae927beb8a3f9cb59e6df0780dcbcb0392438e1ee84d01719bdcb666abee6836

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
